### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by lgvz**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/xor_name/12)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @dirvine

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/lib.rs, line 245 \[r1\]](https://reviewable.io:443/reviews/maidsafe/xor_name/12#-K9coSb7ljwYvEObqpiD:-K9coSb7ljwYvEObqpiE:279432402) ([raw file](https://github.com/maidsafe/xor_name/blob/15f817ecc328eca33f5f1cb457118ef1ecc0ff51/src/lib.rs#L245)):*
again thanks 

---

*[src/lib.rs, line 258 \[r1\]](https://reviewable.io:443/reviews/maidsafe/xor_name/12#-K9coOQuFgWgudrhMVvw:-K9coOQuFgWgudrhMVvx:260872021) ([raw file](https://github.com/maidsafe/xor_name/blob/f82f5c7732afa28f28af7fe0aa3eb22dad1db14b/src/lib.rs#L258)):*
Cheers 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/xor_name/12)*

**Comment by NickLambert** [comment]
Hey @lgvz,

Thanks for the additional work, we would like to show our gratitude in the form of some BTC. Can you confirm which address you would like us to send it to?

**Comment by lgvz** [comment]
@NickLambert 34gvkJjAiZU35oFkvBpvLNnxQXSDB5ogw1. Thanks :)

**Comment by NickLambert** [comment]
BTC on the way, thanks again!

**Pull request merged**
